name: chart-feature-toggle-api pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-library
    type: github
    ref: helm-publish-step-for-preferred-dir-layout
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'HMCTS Github'

jobs:
- job: Validate
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/validate.yaml@cnp-library
    parameters:
      chartName: charts/feature-toggle-api
      chartReleaseName: chart-feature-toggle-api-ci-test
      chartNamespace: chart-tests

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn: Validate
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/release.yaml@cnp-library
    parameters:
      packageName: feature-toggle-api
      chartName: charts/feature-toggle-api
      chartReleaseName: chart-feature-toggle-api
      chartNamespace: chart-tests
