version: '2.1'

services:
  feature-toggle-api:
    extends:
      file: docker-compose-core.yml
      service: service
    depends_on:
      feature-toggle-database:
        condition: service_healthy
  feature-toggle-database:
    extends:
      file: docker-compose-core.yml
      service: database
    volumes:
      - feature-toggle-database-data:/var/lib/postgresql/data

volumes:
  feature-toggle-database-data:
