java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  registerAdditionalDns:
    enabled: false
    primaryIngressHost: ${SERVICE_FQDN}
    prefix: www
  environment:
    FEATURES_DB_HOST: ${SERVICE_NAME}-ft-db