postgresql:
  enabled: true
  
importer:
  kvSecretRef: kvcreds
  
java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  registerAdditionalDns:
    enabled: false
    primaryIngressHost: ${SERVICE_FQDN}
    prefix: www
