{{- if .Values.importer.cron.enabled }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "hmcts.releaseName" . }}-importer
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "hmcts.releaseName" . }}-importer
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ template "hmcts.releaseName" . }}
spec:
  schedule: {{ .Values.importer.cron.schedule | quote }}
  concurrencyPolicy: {{ .Values.importer.cron.concurrencyPolicy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "hmcts.releaseName" . }}-importer
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ template "hmcts.releaseName" . }}-importer
        spec:
          containers:
          - image: {{ .Values.importer.cron.image }}
            name: {{ template "hmcts.releaseName" . }}-importer
            imagePullPolicy: {{ .Values.importer.cron.imagePullPolicy }}
            command: ["sh", "-c", "{{ .Values.importer.cron.command }}"]
            env:
              - name: FEATURE_TOGGLE_API_URL
                value: "http://{{ template "hmcts.releaseName" . }}/api/ff4j/store/features/"
              - name: PERMISSIONS
                value: "{{ .Values.importer.cron.permissions }}"
              - name: VERBOSE
                value: "true"
          restartPolicy: Never
      backoffLimit: 4
{{- end }}